### ISSUE TITLE
cannot load such file -- gettext/tools/task

### ISSUE THREAD

**Issue by mreinsch** [grosser/gettext_i18n_rails#106]
This is maybe mainly a documentation issue, but I just ran into this.

We used 

```
gem 'gettext', '>=3.0.2', :require => false, :group => :development
```

in our Gemfile as suggested by the readme. After updating to 1.0.0, we couldn't run rake in our production environment anymore though. This is because the railtie.rb loads gettext_i18n_rails/tasks.rb which requires gettext.

Also, I assume that when using .po files instead of .mo files, you'll need gettext in the production group, right?

**Comment by modreoci** [comment]
Hi guys... I'm newbie in Rails and I don't know how to solve the same problem on Heroku (I'm coding on ide.c9.io and deploying code to Heroku).

**Comment by grosser** [comment]
are you on > 1.0.1 ? do you have a backtrace ? -> run rake with --trace to get one

**Comment by modreoci** [comment]
Hi Michael.
I'm on the latest version (rails version is 4.1.8) and here is the
backtrace:

Running `rake db:migrate --trace` attached to terminal... up, run.1784
rake aborted!
LoadError: cannot load such file -- gettext/tools/task
/app/vendor/bundle/ruby/2.0.0/gems/gettext_i18n_rails-1.2.0/lib/gettext_i18n_rails/tasks.rb:1:in
`require'
/app/vendor/bundle/ruby/2.0.0/gems/gettext_i18n_rails-1.2.0/lib/gettext_i18n_rails/tasks.rb:1:in
`<top (required)>'
/app/Rakefile:4:in `require'
/app/Rakefile:4:in `<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in
`load'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in
`load_rakefile'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:689:in
`raw_load_rakefile'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:94:in
`block in load_rakefile'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in
`standard_exception_handling'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:93:in
`load_rakefile'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:77:in
`block in run'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in
`standard_exception_handling'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in
`run'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top
(required)>'
/app/vendor/bundle/ruby/2.0.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.0.0/bin/rake:23:in `<main>'

​Thnx in advance ;-)​

Radek Hrančík

2015-02-19 17:30 GMT+01:00 Michael Grosser <notifications@github.com>:

**Comment by grosser** [comment]
looks like you are loading the tasks directly instead of letting the raltie handle that

it deals with gettext not being available: https://github.com/grosser/gettext_i18n_rails/blob/1261d2f2817af42e637f4208264521e2cf13ba18/lib/gettext_i18n_rails/railtie.rb

so either remove the require in the Rakefile and let rails require the railtie on it's own or do a similar logic

**Comment by modreoci** [comment]
I set it according to the instructions in the Readme.md file:
-
## Setup
### Installation

```ruby
# Gemfile
gem 'gettext_i18n_rails'

# Rakefile
require 'gettext_i18n_rails/tasks'
```

Here is my Rakefile:
-
```ruby
require 'gettext_i18n_rails/tasks'
require File.expand_path('../config/application', __FILE__)
Rails.application.load_tasks
```

and Gemfile:
-
```ruby
source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.1.8'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'bootstrap-sass'
gem 'rails-i18n'
gem 'gettext_i18n_rails'
gem 'globalize'
gem 'twitter_cldr'
gem 'sass-rails', '~> 5.0.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
  gem 'gettext', :require => false
end

group :test do
  gem 'minitest-reporters'
  gem 'mini_backtrace'
  gem 'guard-minitest'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'unicorn'
end
```

**Comment by grosser** [comment]
have to fox the readme then :D
does it work fine without the require ?

**Comment by modreoci** [comment]
Yesss...! It works. Thnx!
Does it mean that "require..." statement in Rakefile is not necessary for full functionality? :-o

**Comment by grosser** [comment]
yes since the railtie already requires it when necessary + catches the
exception when gettext is not available

**Comment by modreoci** [comment]
So, why there is that instruction in the readme if it generates this error on production env and is not necessary in fact?

**Comment by grosser** [comment]
because the maintainer is incompetent ... I'll have to talk to him ;)

**Comment by modreoci** [comment]
:-))))))) Can you help me with something other?

**Comment by grosser** [comment]
just make a new issue so discussion stays on topic
