### ISSUE TITLE
Support for context prefixes

### ISSUE THREAD

**Issue by dgilperez** [grosser/gettext_i18n_rails#118]
Hi!

I'm trying to use context aware translations as explained in `ruby-gettext` docs: http://rubydoc.info/gems/gettext/#Usage , in the form:

```
p_("Printer","Open") <=> p_("File","Open")
```

When I tried to `rake gettext:find` one of those translations, the task failed with an obscure `comparison of Array with Array failed` error. 

Is this supported at all by `gettext_i18n_rails`? 

Thanks!

**Comment by bdcheung** [comment]
> meh ... makes everything more complicated, key-value store FTW :D

With respect, I disagree.  Translations are context-specific and having support for the `msgctxt` key is an important function.

As a real-world example, consider your common login page.  You'll have the string "Login" as a page title, a page header, and as a button label.  For most non-English languages, you need two different translations for the title/header and the button (e.g. in Spanish, it would be 'Acceso' for the title/header and 'Acceder' for the button).

Without context, how would the translator know which to use?

**Comment by grosser** [comment]
use `Button|Login` and `Header|Login` or something like that ?

**Comment by bdcheung** [comment]
That's a workaround but it sidesteps the standard in translation services.  https://www.gnu.org/software/gettext/manual/html_node/Contexts.html and http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html are additional sources supporting the use of `msgctxt`.

**Comment by grosser** [comment]
they all also support `Button|Login` ... and that is easier to automatically scape from pages too ... so idk why anyone would prefer msgctxt.

**Comment by bdcheung** [comment]
I may work on a PR regardless as my content team is recommending we use `msgctxt` 😄

**Comment by grosser** [comment]
ask them why they prefer that, would be nice to have some context ... afaik
there is no difference

**Comment by grosser** [comment]
could also add a tiny script to automatically split all translations from
foo|bar into msgctxt and then nothing needs to change ...
