### ISSUE TITLE
Unable to add languages

### ISSUE THREAD

**Issue by qwerty55** [grosser/gettext_i18n_rails#134]
Problem: Any attempt to add languages with rake results in "Don't know how to build task 'gettext:add_language'" errors.

Error:

root@sandbox:/var/examplesite# rake gettext:add_language[en]
rake aborted!
Don't know how to build task 'gettext:add_language'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in`<main>'
(See full trace by running task with --trace)

Steps to reproduce:

1.) create new rails 4 project
2.) add "gem 'gettext_i18n_rails'" to Gemfile & bundle install
3.) run "rake gettext:add_language[en]"

Install Gems:
**\* LOCAL GEMS ***

actionmailer (4.2.1, 4.0.0)
actionpack (4.2.1, 4.0.0)
actionview (4.2.1)
activejob (4.2.1)
activemodel (4.2.1, 4.0.0)
activerecord (4.2.1, 4.0.0)
activerecord-deprecated_finders (1.0.4, 1.0.3)
activesupport (4.2.1, 4.0.0)
arel (6.0.0, 4.0.2, 4.0.0)
atomic (1.1.14)
bcrypt (3.1.10)
bcrypt-ruby (3.1.5, 3.1.2)
bigdecimal (1.2.6)
binding_of_caller (0.7.2)
builder (3.2.2, 3.1.4)
bundler (1.9.9, 1.8.4)
bundler-unload (1.0.2)
byebug (5.0.0)
cancan (1.6.10)
coffee-rails (4.1.0, 4.0.0)
coffee-script (2.4.1, 2.2.0)
coffee-script-source (1.9.1.1, 1.6.3)
columnize (0.9.0)
debug_inspector (0.0.2)
devise (3.5.1, 3.1.0)
devise-i18n (0.12.0, 0.9.0)
devise_ldap_authenticatable (0.8.4)
erubis (2.7.0)
execjs (2.5.2, 2.0.1)
executable-hooks (1.3.2)
fast_gettext (0.9.2)
gem-wrappers (1.2.7)
gettext_i18n_rails (1.2.3)
globalid (0.3.5)
hike (1.2.3)
i18n (0.7.0, 0.6.5)
io-console (0.4.3)
jbuilder (2.2.16, 1.5.1)
jquery-rails (4.0.3, 3.1.2, 3.0.4)
json (1.8.3, 1.8.2, 1.8.1)
loofah (2.0.2)
mail (2.6.3, 2.5.4)
mime-types (2.6.1, 1.25.1, 1.25)
mini_portile (0.6.2)
minitest (5.7.0, 4.7.5)
multi_json (1.11.0, 1.8.0)
mysql2 (0.3.18)
net-ldap (0.5.1)
nokogiri (1.6.6.2)
orm_adapter (0.5.0, 0.4.0)
polyglot (0.3.5, 0.3.3)
psych (2.0.8)
rack (1.6.1, 1.5.3, 1.5.2)
rack-test (0.6.3, 0.6.2)
rails (4.2.1, 4.0.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.6)
rails-html-sanitizer (1.0.2)
rails-i18n (4.0.4, 0.7.4)
railties (4.2.1, 4.0.0)
rake (10.4.2, 10.1.0)
rdoc (4.2.0, 3.12.2)
responders (2.1.0, 1.1.2)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.4.14, 3.2.10)
sass-rails (5.0.3, 4.0.0)
sdoc (0.4.1, 0.3.20)
spring (1.3.6)
sprockets (3.2.0, 3.1.0, 2.12.3, 2.10.0)
sprockets-rails (2.3.1, 2.0.1, 2.0.0)
sqlite3 (1.3.10)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5, 0.1.3)
tilt (1.4.1)
treetop (1.4.15)
turbolinks (2.5.3)
twitter-bootstrap-rails (2.2.8)
tzinfo (1.2.2, 0.3.44, 0.3.37)
uglifier (2.7.1)
warden (1.2.3)
web-console (2.1.2)

Ruby:

ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by grosser** [comment]
I think you might be missing: https://github.com/grosser/gettext_i18n_rails#optional

**Comment by krukgit** [comment]
Take note that `gettext` needs to be `>=3.0.2`. It wasn't working for me either until I realized I'm using gettext `2.3.9`.

**Comment by grosser** [comment]
are you on latest gettext_i18n_rails ? <-> it has a strict require for gettext, so that should not happen :(

**Comment by riseriyo** [comment]
Hello, I know the OP issue is almost 3 years old, but did anyone resolved what the OP had stated? I'm having a similar issue. 

This is what I am running:
**ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]**

*** LOCAL GEMS ***

actioncable (5.1.6)
actionmailer (5.1.6)
actionpack (5.1.6)
actionview (5.1.6)
activeadmin (1.2.1)
activejob (5.1.6)
activemodel (5.1.6)
activerecord (5.1.6)
activesupport (5.1.6)
arbre (1.1.1)
arel (8.0.0)
awesome_print (1.8.0)
bcrypt (3.1.11)
bcrypt-ruby (3.1.5)
bigdecimal (default: 1.3.4)
bindex (0.5.0)
bootstrap-sass (3.1.1.1)
builder (3.2.3)
bundler (1.16.1)
bundler-unload (1.0.2)
cmath (default: 1.0.0)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5)
crass (1.0.4)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
encryptor (1.3.0)
erubi (1.7.1)
etc (default: 1.0.0)
execjs (2.7.0)
executable-hooks (1.4.2)
**fast_gettext (1.6.0)**
fcntl (default: 1.0.0)
ffi (1.9.23)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
formtastic (3.1.5)
formtastic_i18n (0.6.0)
gdbm (default: 2.0.0)
gem-wrappers (1.3.2)
**gettext (3.2.9)
gettext_i18n_rails (1.8.0)**
globalid (0.4.1)
haml (5.0.4)
has_scope (0.7.2)
**i18n (1.0.0)**
inherited_resources (1.8.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
jquery-rails (4.3.1)
json (default: 2.1.0)
kaminari (1.1.1)
kaminari-actionview (1.1.1)
kaminari-activerecord (1.1.1)
kaminari-core (1.1.1)
libv8 (3.16.14.19 x86_64-linux)
locale (2.1.2)
loofah (2.2.2)
mail (2.7.0)
method_source (0.9.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.10.3)
net-telnet (0.1.1)
nio4r (2.3.0)
nokogiri (1.8.2)
openssl (default: 2.1.0)
pg (1.0.0)
polyamorous (1.3.3)
power_assert (1.1.1)
psych (default: 3.0.2)
puma (3.11.4)
rack (2.0.4)
rack-test (1.0.0)
**rails (5.1.6)**
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.4)
railties (5.1.6)
**rake (12.3.1, 12.3.0)**
ransack (1.8.8)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (default: 6.0.1)
redis (3.0.7)
ref (2.0.0)
responders (2.4.0)
ruby-graphviz (1.2.3)
**ruby_parser (3.11.0)**
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.5.6)
sass-listen (4.0.0)
sass-rails (5.0.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
sexp_processor (4.11.0)
sir_cachealot (0.6.7)
sprockets (3.7.1)
sprockets-rails (3.2.1)
sqlite3 (1.3.13)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
temple (0.8.0)
test-unit (3.2.7)
text (1.3.1)
therubyracer (0.12.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
tzinfo (1.2.5)
uglifier (4.1.9)
web-console (3.5.1)
webrick (default: 1.4.2)
websocket-driver (0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.3.0)
zlib (default: 1.0.0)

root@sandobx ~/src/orders $ rake gettext:add_language[fr] --trace
rake aborted!
Don't know how to build task 'gettext:add_language' (see --tasks)
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:159:in `invoke_task'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/me/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.5.1/bin/rake:23:in `load'
/home/me/.rvm/gems/ruby-2.5.1/bin/rake:23:in `<main>'
/home/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'

Thanks well in advance.

**Comment by riseriyo** [comment]
I did the following:
- Added the gems to Gemfile.
- Ran 'bundle install'
- Had to comment out active_admin (activeadmin-1.2.1).
- Ran the command again, and it worked!
root@sandbox ~/src/orders $ rake gettext:add_language[fr]
/home/me/.rvm/gems/ruby-2.5.1/gems/redis-3.0.7/lib/redis/client.rb:386: warning: constant ::Fixnum is deprecated
mkdir -p /home/me/src/orders/locale/fr

Hope this helps anyone else out there. Cheers.

**Comment by grosser** [comment]
thx for the update!
