### ISSUE TITLE
Use with third-party gems

### ISSUE THREAD

**Issue by gmq** [grosser/gettext_i18n_rails#135]
Hi,
I'm currently converting a website to use gettext using this gem but I was wondering, what's the best way to deal with third-party gems?

Modifying the gems to use _() instead of t() seems extreme. Converting from yaml to po and then back yaml feels inefficient.

**Comment by grosser** [comment]
There is also an I18n backend that reads gettext files ...
I18n.t might even work ... give it a try .. if not ... you can try making it work :)

**Comment by gmq** [comment]
What I meant was: if I install Devise with bundle I have no access to the gem, it ends up in a system folder hidden from view. The only thing I can do is to use a yaml file. I was wondering if there's a standard way to deal with that, maybe translating those yaml files with gettext (???) or something else that I'm missing. Thanks!

**Comment by grosser** [comment]
The translations inside devise are accessible from rails with the default
backend, you most likely want to translate them, so find them and add them
to your gettext keys,
after they are translated you should be able to use them.

Finding them looks something like this:

Dir[Gem::Specification.find_by_name("device").gem_dir.join("config/**/*.yml")]

then you make them accessible to gettext:find by writing to a static file
or add them to the po by hand.

On Fri, Jun 12, 2015 at 11:53 AM, Guillermo Moreno <notifications@github.com

**Comment by gmq** [comment]
Thanks, that pointed me in the right direction and I was able to make it work.

**Comment by grosser** [comment]
can you elaborate on how you got it working for future googlers :)

**Comment by gmq** [comment]
I made a rake task that:

1. Lists the files found by `Dir[Gem::Specification.find_by_name("devise").gem_dir << "/config/**/*.yml"]`
2. Flattens the keys in the yml files
3. Saves the keys as gettext strings `N_('sample.key')` in a static file in the locale folder.

After that I let `gettext:find` do its job.

**Comment by grosser** [comment]
Sweet!
