### ISSUE TITLE
gettext:find can not find translations in .pdf.prawn files

### ISSUE THREAD

**Issue by Focinfi** [grosser/gettext_i18n_rails#139]
I am working on produce pdf using gem `prawn` and `prawnto`, but when I run `rake gettext:find`, it missed the translations in .pdf.prawn files.

**Comment by grosser** [comment]
you can overwrite `files_to_translate` in your Rakefile (I know ... it's a horrible way to do things ... but that's how rake works ... would be awesome if you can make a PR to change this to class methods)

```
# Rakefile

# overwrite what files gettext:find will look through
Object.prepend(Module.new{
  def files_to_translate
    super + Dir['app/foo/*.prawn']
  end
})
```

**Comment by Focinfi** [comment]
@grosser thanks for your reply.
