### ISSUE TITLE
gettext:find does not find interpolated strings in .rb files

### ISSUE THREAD

**Issue by ceres629** [grosser/gettext_i18n_rails#146]
Not sure if this is an issue with gettext_i18n_rails  or the getext gem but...
Running gettext:find doesn't seem to find interpolated strings in .rb files.

    #In a .rb file
    test = _("Test: this key is found by gettext")
    test2 = "#{_("Test: this key is not found by gettext")}"

In .haml files however, the above examples both work fine and gettext:find correctly identifies both as being strings to be translated.

**Comment by grosser** [comment]
more a bug with ruby-parser vs the finder implementation ... so I'd say fix
should go into gettext

**Comment by ceres629** [comment]
Got it!
Thanks for the quick response!
