### ISSUE TITLE
invalid option: --location

### ISSUE THREAD

**Issue by graaff** [grosser/gettext_i18n_rails#152]
With gettext_i18n_rails 1.5.0 I've started to see "invalid option: --location" output when running the "gettext:find" task. I assume this happens because the default_options are now also passed to msgcat, but msgcat does not recognize the --location (or --no-location) options. Perhaps these options should be removed from the msgcat specific options?

**Comment by grosser** [comment]
sounds right, can you open a PR to change it ?
