### ISSUE TITLE
Possible regression with haml files

### ISSUE THREAD

**Issue by dgilperez** [grosser/gettext_i18n_rails#156]
After updrading to latest version, my haml files stopped working, ie. translations are not found / removed from my app.po files.

`rake gettext:find --trace` seems to be skipping haml files (I see `** Invoke app/<haml-file> (first_time, not_needed)` for each haml file. 

When I do `rake gettext:pack` I see a lot of lines with the message `No haml library could be found: haml or hamlit` which I believe related to #151. 

I'm using:
* haml (4.0.7)
* haml-rails (0.9.0)
* gettext (~> 3.2)
* gettext_i18n_rails (~> 1.7.1)

Anyone with the same problem? How may I debug this?

**Comment by grosser** [comment]
`bundle show gettext_i18n_rails` and add some puts around the area where it tries to load haml (lib/gettext_i18n_rails/base_parser.rb:28) ... somehow that fails :(

make sure to use `bundle exec rake ` so the gems are available ...

**Comment by dgilperez** [comment]
My `puts` there are not showing anything 😞 . I keep seeing `** Invoke app/<haml-file> (first_time, not_needed)` messages, new translations are not found. When I change the `.po` file directly and run `(bundle exec) rake gettext:pack`, now I don't see those `No haml library could be found` errors. Weird.

**Comment by dgilperez** [comment]
Ok, got it (https://github.com/grosser/gettext_i18n_rails/pull/154/files#diff-2b9d7692c58d6211213d94fc859b9747R26). Preparing a patch.
