### ISSUE TITLE
Parsing .coffee files in views as erb

### ISSUE THREAD

**Issue by coffeebite** [grosser/gettext_i18n_rails#158]
I have files with .js.coffee extension in my rails views. Rails automatically parses .coffee files in views as ERBs without requiring the .erb extension. I'd like the `gettext:find` task to parse my .coffee files in views folders like ERB files and extract translations from them. How do I do that? I have changed the `files_to_translate` method by adding this to `lib/tasks/gettext.rake`:

```ruby
namespace :gettext do
  def files_to_translate
    Dir.glob("{app,lib,config,locale}/**/*.{rb,erb}") + Dir.glob("app/views/**/*.coffee")
  end
end
```

I also added this line in `gettext.rake`

```ruby
GetText::ErbParser.init(extnames: ['.erb', '.coffee'])
```

But it doesn't work.

**Comment by grosser** [comment]
not sure even js is supported ... maybe find that first ... alternatively
write some custom script that extracts the i18n calls and dumps them into a
addional.rb file that gettext will that understand/parse

**Comment by coffeebite** [comment]
Thanks for the response, Mike. I can try that. Though, is there a simple way for me to specify that, on top of .erb and .rhtml, .coffee files should also be processed by the Erb parser?

**Comment by grosser** [comment]
Don't know how that would be done, but should be possible if you find
whatever does the erb parsing ..

**Comment by coffeebite** [comment]
Thanks, Mike. I'll dig around.

**Comment by artemv** [comment]
@coffeebite, parsing of both JS and Coffee (and some other blends of JS including JSX now) are supported if you add https://github.com/webhippie/gettext_i18n_rails_js gem.

**Comment by grosser** [comment]
might want to link that in the readme ... closing for now ...
