### ISSUE TITLE
Raw text in haml files are not translated

### ISSUE THREAD

**Issue by neohunter** [grosser/gettext_i18n_rails#159]
I've a haml file with something like:

```
%h1= _('This text is translated')
%p This is a text I would like to translate, but is not.
```

The h1 text is transalted, but the P is not, do you support raw text or not? is not clear in the readme.

I found this gem but is frmo 6 years ago, not sure if it works.

https://github.com/nu7hatch/haml-magic-translations

**Comment by grosser** [comment]
raw text should never be translated ...
