### ISSUE TITLE
Difference between app.po and app.edit.po

### ISSUE THREAD

**Issue by peterwake** [grosser/gettext_i18n_rails#163]
Could someone please explain what these files are for - I am sure there is a reason for both! Which one should be sent to someone to translate? Many thanks.

**Comment by grosser** [comment]
Where are these files ?

... .po files are supposed to exist 1 per language ... the app.edit.po might have a different set of translations ...

**Comment by peterwake** [comment]
If I run

```
$ rake gettext:find
```

I get this output on the terminal:
```
touch config/locales/de/app.po.time_stamp
rm -f config/locales/en/app.edit.po
cp config/locales/en/app.po config/locales/en/app.edit.po
touch config/locales/en/app.po.time_stamp
rm -f config/locales/zh_CN/app.edit.po
cp config/locales/zh_CN/app.po config/locales/zh_CN/app.edit.po
touch config/locales/zh_CN/app.po.time_stamp
```

And then both the app.po and app.edit.po files change to add new translations, and the only difference between them is the line

`"POT-Creation-Date: 2016-09-06 19:54+0100\n"` 

I'm really just wondering what purpose it serves to have both these files. Or is one a backup file?

**Comment by grosser** [comment]
no idea where this .edit is coming from ... might be some strange leftover
... try deleting it ?

**Comment by peterwake** [comment]
On further digging it the rake command jumps into a gettext rake command.

There is a discussion on this here: https://github.com/ruby-gettext/gettext/issues/36
