### ISSUE TITLE
gettext for database variables

### ISSUE THREAD

**Issue by CR4567** [grosser/gettext_i18n_rails#173]
Hey,

maybe this question is stupid but I didn't find any help online....
I have some variables coming from the database which should be translated.
E.g.:
Object is called "Event" with a field "translation_name" which could be "inactivity, alarm, etc."

Right now I'm using it in the code in this way:
_("Event|#{event.event_type.translation_code}")
and in my pot file I have
msgid "Event|inactivity"
msgstr ""

This works!
But when I use gettext:find it deletes this entries and generates a new one with
msgid "Event|#{event.event_type.translation_code}"

It kind of make sense, but obviously is not working....

Could someone help with this? Is it the complete wrong way of translate DB strings?
or is it the wrong way to call it?

or just a problem with gettext:find?

I appreciate every help :-)

**Comment by grosser** [comment]
`msgid "Event|#{event.event_type.translation_code}"` should not have been captured ... that's a bug in gettext or ruby_parser ... if you want to have those unfindable translations then add them to a file that is never loaded

```
_("Event|inactivity")
_("Event|foobar")
... etc
```
