### ISSUE TITLE
Let rake gettext:find find rails t() entries

### ISSUE THREAD

**Issue by mjacobus** [grosser/gettext_i18n_rails#182]
Hey there

We are working on this one project, and it would be super useful to use gettext through the I18n API. The only thing hindering us from following down that path is that `rake gettext:find` won't take into account the `<%= t('strings internationalized with rails t view helper') %>`, or `I18n.t('xyz')`.

If you think that it could be a nice optional feature, I would be more than happy to work on a PR. If that is not a feature you folks would like to add, I can try extending it at our end.

Anyways, could you folks give me some directions on how to accomplish that? I see there is some hardcore ruby parsing going on under the hood, and I am not yet familiarized with it.

Thank you in advance.

**Comment by grosser** [comment]
the gettext parser this uses lives in https://github.com/ruby-gettext/gettext so most likely need to go there to figure this out

https://github.com/grosser/gettext_i18n_rails/blob/master/lib/gettext_i18n_rails/tasks.rb#L65
uses https://github.com/ruby-gettext/gettext/blob/master/lib/gettext/tools/task.rb
