### ISSUE TITLE
This gem seems to annihilate I18n.available_locales

### ISSUE THREAD

**Issue by gregschmit** [grosser/gettext_i18n_rails#186]
I have a Rails 6 app that has some existing use of the I18n yaml files (active scaffold). I want to use gettext for actual translation, but adding this gem yields:

```
[6] pry(main)> I18n.available_locales
=> []
```

The only way I found to fix it is to add `require: false` in the Gemfile, but then the setup rake task isn't found.

Is this behavior expected? Is there a way to set `available_locales` back to the full list?

**Comment by grosser** [comment]
I'd think this comes from https://github.com/grosser/gettext_i18n_rails/blob/1735aedd8148f6782831e64ec5718c436b5103c8/lib/gettext_i18n_rails/backend.rb#L15
and if it's empty that would mean no languages were setup using gettext ... is that not the case ?

**Comment by gregschmit** [comment]
So I resolved this by setting I18n locales explicitly like I showed in my last comment, and then gettext and i18n work great side-by-side (choosing locales works normally and `I18n.locale` can be set independent of `FastGettext.locale`). It's just confusing that this gem clears out the `I18n.available_locales`. The principle of least surprise seems like it should not affect that properly at all because these are separate translation gems.

What is the purpose of `I18n.backend = GettextI18nRails::Backend.new`?

**Comment by grosser** [comment]
to make it use that backend 🤷 

the locales should be the locales available in gettext, so idk why it would be cleared out

**Comment by gregschmit** [comment]
Maybe I misunderstand the purpose of this project. I thought this project was to enable the use of FastGettext **alongside** of I18n. I feel like this would be especially important when migrating an app from I18n to gettext. I don't want I18n to use gettext, I want to use gettext (i.e., I want my `I18n.t(:whatever)` strings to stay behaving the same, and I want to replace them over time with `_("whatever")`. That seems to be how this project works right now, and it's working great in my own app. I can't wait to get rid of I18n entirely, but we still have some customers with legacy I18n yaml files that are not read to switch. So that's why it confuses me why we would change I18n's backend and break it.

I will see if there is a bug, but I also have several locales translated and they are working when I set `FastGettext.locale`, but FastGettext's `available_locales` is nil. That's a separate issue though.

**Comment by grosser** [comment]
From readme: `use any other I18n backend as extension/fallback`so that's your usecase 👍 
locales are supposed to come from gettext since that was supposed to be the main languages
you might have to use the [chain backend](https://github.com/grosser/fast_gettext/blob/master/lib/fast_gettext/translation_repository/chain.rb) to have that fallback work properly, I have not played with this in a long time

**Comment by gregschmit** [comment]
Ok; yeah things do work perfectly fine, just confused me when it made available_locales empty, but this issue is resolved.
