### ISSUE TITLE
HAML support for context (p_)

### ISSUE THREAD

**Issue by adam-h** [grosser/gettext_i18n_rails#199]
Translated strings in `haml` extract incorrectly compared to `rb` files.

Example `my_module_helper.rb`:
```rb
module MyModuleHelper
  def my_method
    p_("Context in ruby", "Ruby")
  end
end
```

Example `test.html.haml`:
```haml
.flex
  =p_("Context in haml", "Haml")
```

Results in the following in my `app.pot` after running `bin/rake gettext:find`:
```pot
msgctxt "Context in ruby"
msgid "Ruby"
msgstr ""

msgid "Context in haml"
msgstr ""
```

When I would expect them both to have the `msgctxt` context.

I am guessing the issue is in https://github.com/grosser/gettext_i18n_rails/blob/cc5bc2f492bd63be8b07788540c369bd913d3b4a/lib/gettext_i18n_rails/ruby_gettext_extractor.rb#L102-L111 with it not handling this kind of call 🤷

**Comment by grosser** [comment]
PR welcome, looks like you already found where it is hiding :D

**Comment by adam-h** [comment]
Thanks! When I dug into this I found this worked, and was vastly simpler, just using the parser provided already by `GetText`: https://github.com/grosser/gettext_i18n_rails/pull/201
