### ISSUE TITLE
rake gettext:store_model_attributes breaks with ActiveSupport 7 and Ruby 3.1.4

### ISSUE THREAD

**Issue by joostvanrijn** [grosser/gettext_i18n_rails#202]
There have been things going on in ActiveSupport::DescendantsTracker, because Ruby 3.1 supplies a native (faster) `subclasses` method.

I believe this breaks the `::ActiveRecord::Base.direct_descendants` used in the model attribute finders, because `direct_descendants` is no longer defined.

I could fairly easily remedy this by replacing `direct_descendants` with `subclasses`. But I'm not sure if this is the way to go.

ruby: 3.1.4
rails: 7.1.1

If this is something that should be fixed in this gem I'd be more than happy to contribute, but I'm new to it and not really sure where to start.

**Comment by grosser** [comment]
sounds great, if you can make subclasses work then that'd be awesome
... we can limit the supported ruby/rails versions if that helps or see how hard it is to support both old and new
